application: awesomescores
version: 8
runtime: java

welcome_files:
- index.html
- awesome.css
- handheld.css 


precompilation_enabled: true

handlers:
- url: /game.html
  secure: always
  servlet: org.davidliebman.webapps.awesomescores.server.GameHttpServlet

- url: /
  secure: always
  servlet: org.davidliebman.webapps.awesomescores.server.GreetingServiceImpl


