application: awesomescores
version: 3
runtime: java

welcome_files:
- index.html
- awesome.css
- handheld.css 

precompilation_enabled: true

handlers:
- url: /index.html
  login: required
  servlet: org.davidliebman.webapps.awesomescores.server.GreetingServiceImpl
  init_params:
    security: user
  name: userconsole

- url: /game.html
  jsp: /game.jsp

#- url: /admin/index.html
#  login: admin
#  servlet: org.davidliebman.webapps.awesomescores.server.GreetingServiceImpl
#  init_params:
#    security: admin
#  name: adminconsole



- url: /game.html
  #login: optional
  jsp: /game.jsp
  init_params:
    security: game
  name: game



