application: awesomescores
version: 1
runtime: java

welcome_files:
- Awesome_scores.html
- Awesome_scores.css



handlers:
- url: /*
  login: required
  servlet: org.davidliebman.webapps.awesomescores.server.GreetingServiceImpl
  init_params:
    bgColor: yellow
  name: adminconsole

- url: /admin/*
  login: admin
  servlet: org.davidliebman.webapps.awesomescores.server.GreetingServiceImpl
  init_params:
    bgColor: blue
  name: userconsole
