application: awesomescores
version: 1
runtime: java

welcome_files:
- Awesome_scores.html
- Awesome_scores.css

handlers:
- url: /*
  login: required
  servlet: org.davidliebman.webapps.awesomescores.server.GreetingServiceImpl
  init_params:
    security: user
  name: userconsole

- url: /admin/
  login: admin
  servlet: org.davidliebman.webapps.awesomescores.server.GreetingServiceImpl
  init_params:
    security: admin
  name: adminconsole

- url: /_ah/login
  login: required
  
