application: awesomescores
version: 3
runtime: java

welcome_files:
- index.html
- awesome.css
- handheld.css 

precompilation_enabled: true

handlers:
- url: /game.html
  jsp: /game.jsp

- url: /test.html
#  login: required
  servlet: org.davidliebman.webapps.awesomescores.server.GameHttpServlet

- url: /
#  login: required
  servlet: org.davidliebman.webapps.awesomescores.server.GreetingServiceImpl
#  init_params:
#    security: user
#  name: userconsole


