application: awesomescores
version: 3
runtime: java

welcome_files:
- Awesome_scores.html
- Awesome_scores.css
- handheld.css 

handlers:
- url: /admin/Awesome_scores.html
  login: admin
  servlet: org.davidliebman.webapps.awesomescores.server.GreetingServiceImpl
  init_params:
    security: admin
  name: adminconsole

- url: /*
  login: required
  servlet: org.davidliebman.webapps.awesomescores.server.GreetingServiceImpl
  init_params:
    security: user
  name: userconsole

