application: awesomescores
version: 4
runtime: java

welcome_files:
- index.html
- awesome.css
- handheld.css 

precompilation_enabled: true

handlers:
- url: /game.html
#  login: required
  servlet: org.davidliebman.webapps.awesomescores.server.GameHttpServlet

- url: /
#  login: required
  servlet: org.davidliebman.webapps.awesomescores.server.GreetingServiceImpl


